
mobile_base_controller:
  type: "ackermann_steering_controller/AckermannSteeringController"
  rear_wheel: 'traction_wheel_joint'
  front_steer: 'steer_contol_joint'
  wheel_separation_h : 1.20809
  wheel_radius: 0.09191
  base_frame_id: base_footprint
  odom_frame_id: odom
  publish_rate: 50
  enable_odom_tf: true
  pose_covariance_diagonal: [0.0001, 0.0001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.0001, 0.0001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # Wheel separation and radius multipliers for odometry calibration.
  # wheel_separation_h_multiplier: 1 # default: 1.0
  # wheel_radius_multiplier    : 1 # default: 1.0
  # Steer position angle multipliers for fine tuning.
  # steer_pos_multiplier       : 0.85


joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50